services:
    db:
        image: postgres:16
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: rpg
        ports:
            - "15432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: